FROM public.ecr.aws/lambda/python:3.10

# Copy function code
COPY app/ ${LAMBDA_TASK_ROOT}/app/

# Copy requirements.txt
COPY requirements.txt ${LAMBDA_TASK_ROOT}/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Command to run the Lambda function
CMD ["app.main.lambda_handler"]
